import React, {useContext, useRef, useState} from 'react';
import {Link, useNavigate} from "react-router-dom";
import logo from "../../images/logo.svg";
import {AuthContext} from "../../context/AuthContext";

import avatar from "../../images/defaultAvatar.svg";
import polygon from "../../images/polygon.svg";
import polygonOnRectangle from "../../images/polygonOnRectangle.svg"
import {CsrfContext} from "../../context/CsrfContext";

const Header = () => {

    const authContext = useContext(AuthContext);
    const csrfContext = useContext(CsrfContext);
    const [showMenu, setShowMenu] = useState(false);
    let redirect = useNavigate();
    const redirectTo = (path: string) => {
        redirect(path);
    };

    function logout() {
        fetch("/logout", {
            method: "POST",
            headers: {
                'Content-Type': 'application/json',
                'X-XSRF-TOKEN': csrfContext?.csrfToken!
            }
        }).then((response) => response.text()).then((data) => {
            // set new csrf token generated by server for this session.
            csrfContext?.setToken(data);
        });
        authContext?.setAuth(false);
        authContext?.setUsername("$anonymous");
    }

    return (
        <header className="header">
            <Link to={"/"} className="logo">
                <img src={logo} alt="logo"/>
            </Link>
            {
                authContext?.auth
                    ?
                    <div className="header__box">
                        <div className="header__user" onClick={() => setShowMenu(!showMenu)}>
                            <img src={avatar} alt="avatar" className={"header__user-avatar"}/>
                            <img src={polygon} alt="polygon"/>
                        </div>
                        <ul className={showMenu ? "user__menu active" : "user__menu"}>
                            <img src={polygonOnRectangle} alt="polygon" className="user__menu-polygon"/>
                            <li className="user__menu-item">
                                {authContext.username}
                            </li>
                            <li className="user__menu-item"
                                onClick={() => redirectTo("/profile/" + authContext?.username)}>
                                Go to profile
                            </li>
                            <li className="user__menu-item"
                                onClick={() => redirectTo("/settings" + authContext?.username)}>
                                Settings
                            </li>
                            <li className="user__menu-item" onClick={() => {
                                logout();
                                redirect("/start");
                            }}>
                                Log out
                            </li>
                        </ul>
                    </div>
                    :
                    <Link to={"/login"}>log in</Link>
            }
        </header>
    );
};

export default Header;